import type { Metadata } from "next";
import { Bangers } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import PageContainer from "@/components/page-container";
import Footer from "@/components/footer";

const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bangers",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1600331961556195"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${bangers.variable} halftone-bg flex min-h-screen flex-col`}>
        <div className="font-bangers flex min-h-screen flex-col">
          <div className="mx-auto flex min-h-screen w-full max-w-7xl flex-col px-2 py-2 sm:px-3 md:px-4">
            <Header />

            <PageContainer className="flex-1">{children}</PageContainer>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
