import type { Metadata } from "next";
import { Bangers } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import PageContainer from "@/components/page-container";
import { Adsense } from "@/components/adsense";
import { AppProvider } from "@/context/app.context";
import Footer from "@/components/footer";

const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bangers",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Adsense pid="ca-pub-1600331961556195" />
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1600331961556195"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body className={`${bangers.variable} bg-principal-seligadev flex min-h-screen flex-col`}>
        <div className="font-bangers halftone-yellow halftone-close overflow-y-full flex min-h-full flex-col">
          <AppProvider>
            <Header />
          </AppProvider>

          <PageContainer>{children}</PageContainer>
          <Footer />
        </div>
      </body>
    </html>
  );
}
