import type { Metadata } from "next";
import { Bangers } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import PageContainer from "@/components/page-container";
import { Adsense } from "@/components/adsense";
import { AppProvider } from "@/context/app.context";

const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bangers",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Adsense pid="ca-pub-1600331961556195" />
      </head>
      <body className={`${bangers.variable} bg-principal-seligadev antialiased`}>
        <div className="font-bangers halftone-bg halftone-close min-h-screen">
          <AppProvider>
            <Header />
          </AppProvider>

          <PageContainer>{children}</PageContainer>
        </div>
      </body>
    </html>
  );
}
